apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: digital-menu-system

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-menu-deployment.yaml
  - rabbitmq-deployment.yaml
  - menu-service-deployment.yaml
  - order-service-deployment.yaml
  - kitchen-service-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

images:
  - name: digital-menu-system/menu-service
    newTag: latest
  - name: digital-menu-system/order-service
    newTag: latest
  - name: digital-menu-system/kitchen-service
    newTag: latest
  - name: digital-menu-system/frontend
    newTag: latest

commonLabels:
  app.kubernetes.io/name: digital-menu-system
  app.kubernetes.io/version: "1.0.0"